// AUTO-GENERATED from the official WHO ICD-11 MMS API (release 2026-01).
// Regenerate with: npx ts-node scripts/fetch-icd11-codes.ts
// Source: https://icd.who.int  —  codes and titles are authoritative WHO data.
export const COMMON_ICD11_CODES = [
  { code: "1A00", short_description: "Cholera", search_terms: ["cholera","vibrio"] },
  { code: "1A07.Z", short_description: "Typhoid fever, unspecified", search_terms: ["typhoid","enteric fever","salmonella typhi"] },
  { code: "1A40.Z", short_description: "Infectious gastroenteritis or colitis without specification of infectious agent", search_terms: ["gastroenteritis","diarrhoea","diarrhea","stomach infection"] },
  { code: "1B10.Z", short_description: "Respiratory tuberculosis, without mention of bacteriological or histological confirmation", search_terms: ["tb","tuberculosis","pulmonary tb","lung tb"] },
  { code: "1C62.Z", short_description: "Human immunodeficiency virus disease without mention of tuberculosis or malaria, clinical stage unspecified", search_terms: ["hiv","aids","immunodeficiency"] },
  { code: "1F40.Z", short_description: "Malaria due to Plasmodium falciparum, unspecified", search_terms: ["malaria","falciparum"] },
  { code: "1F41.Z", short_description: "Plasmodium vivax malaria without complication", search_terms: ["malaria","vivax"] },
  { code: "1F45", short_description: "Malaria without parasitological confirmation", search_terms: ["malaria","clinical malaria"] },
  { code: "3A00.Z", short_description: "Iron deficiency anaemia, unspecified", search_terms: ["anaemia","anemia","iron deficiency"] },
  { code: "5A10", short_description: "Type 1 diabetes mellitus", search_terms: ["diabetes","type 1","t1dm","insulin dependent"] },
  { code: "5A11", short_description: "Type 2 diabetes mellitus", search_terms: ["diabetes","type 2","t2dm","sugar"] },
  { code: "6A70.Z", short_description: "Single episode depressive disorder, unspecified", search_terms: ["depression","depressive","low mood"] },
  { code: "6B00", short_description: "Generalised anxiety disorder", search_terms: ["anxiety","gad","worry"] },
  { code: "8A80.Z", short_description: "Migraine, unspecified", search_terms: ["migraine","headache"] },
  { code: "9A60.Z", short_description: "Conjunctivitis, unspecified", search_terms: ["conjunctivitis","red eye","pink eye"] },
  { code: "BA00.Z", short_description: "Essential hypertension, unspecified", search_terms: ["hypertension","high blood pressure","hbp","bp"] },
  { code: "BA01", short_description: "Hypertensive heart disease", search_terms: ["hypertensive heart disease","hypertension"] },
  { code: "CA00", short_description: "Acute nasopharyngitis", search_terms: ["common cold","cold","coryza","runny nose"] },
  { code: "CA07.0", short_description: "Acute upper respiratory infection, site unspecified", search_terms: ["uri","upper respiratory infection","flu","cough"] },
  { code: "CA42.Z", short_description: "Acute bronchitis, unspecified", search_terms: ["bronchitis","chest infection"] },
  { code: "CA22.Z", short_description: "Chronic obstructive pulmonary disease, unspecified", search_terms: ["copd","chronic bronchitis","emphysema"] },
  { code: "CA23", short_description: "Asthma", search_terms: ["asthma","wheezing","bronchial"] },
  { code: "CA40.Z", short_description: "Pneumonia, organism unspecified", search_terms: ["pneumonia","lung infection","chest infection"] },
  { code: "DA42.Z", short_description: "Gastritis, unspecified", search_terms: ["gastritis","stomach inflammation"] },
  { code: "DA61", short_description: "Peptic ulcer, site unspecified", search_terms: ["peptic ulcer","ulcer","stomach ulcer"] },
  { code: "FA0Z", short_description: "Osteoarthritis, unspecified", search_terms: ["osteoarthritis","arthritis","joint pain"] },
  { code: "GC08.Z", short_description: "Urinary tract infection, site and agent not specified", search_terms: ["uti","urinary tract infection","bladder infection"] },
  { code: "MG26", short_description: "Fever of other or unknown origin", search_terms: ["fever","pyrexia","high temperature"] },
  { code: "ME84.2Z", short_description: "Low back pain, unspecified", search_terms: ["low back pain","lumbago","back pain"] },
  { code: "RA01", short_description: "COVID-19", search_terms: ["covid","coronavirus","covid-19","sars-cov-2"] },
];
